import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import Menu from "@/components/Menu/Menu";
import {ReactNode} from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body >
      <Header />
        <div className={'layoutContainer'}>
          <Menu />
          <main className={'mainContent'}>{children}</main>
        </div>
      </body>
    </html>
  );
}
